language: python

sudo: false

python:
  - "2.7_with_system_site_packages"

install:
  - pip -qqq install --upgrade pip setuptools
  - pip -qqq install -r requirements.txt

env:
  global:
    - PYTHON_ENV=test
  matrix:
    - COMMAND="pre-commit run --all-files"

script: $COMMAND

notifications:
  email: false
